os: linux
dist: xenial
language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- python --version
- pip install --upgrade pip wheel setuptools codecov
install:
- pip install -r requirements-dev.txt
script: pytest
after_success:
- codecov
deploy:
  provider: pypi
  user: wildfish-deployer
  password:
    secure: N7S1NJHn/MoHZDrt4Zl1KI0MuqBfPWVhRbhZstQGnmcXvZ7ks+DFpOdGIVpaCU0GlW/f7VqikdJPuwwDBLI/JQ5UP07usvMsHF4PZambQlK+oPgC59gfEub65JT2NE89eSF+aniEZHDP452UHGh5/lzKgjtZKpEtBzd/U8G1qk5uLvYS7y6jtNPHjpscpM+2tO1QFph2+lYuzxH36rQZQ87M7hFlblErIIR7PDCQ/MyEXuCfY1W0u22ogICJRdzI35vEkugG6/qpnKZXY0VlMg1/SHVOwXYzWxwwYwNvHHiaznZ3myOr0mcFCPNnbteBuY9ApyM/thbgRun33sLfuhZLoE+y/Yx/XQ60kMKj8NzHcwAmC8SwqMBT/g3EtYtIfNrI5gxr1uOKoWO6hk0/+U90cA2fggTvE4EMMemYgw4Ng7IxTKV5o80cAvQChFv2XUne4WkxZJpfTsbW7/vW8sgMTjeyU+bXDXXIsb8hz3LWHvspCdpUb/6+Lmsg/tehNkRTEEAqiC9Z3W+o0hi6Uq4fIjpRMuFCpWVpRM98XRwfMNzQUOMdpJ4EZIarJz1xmZhKZ9lcq50LGiFFVAcaD0VcN9a6aIXPyjqw5ZqbVf9UyJwfBQoHZ5j7XZoxj8w478t0sZ8ePuGSKNJJYPEMpgs4zcDsgJdzLg+fufEg/MM=
  skip_existing: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: wildfish/sphinx-gitref
